# Generated by Django 3.2.3 on 2021-05-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=10)),
            ],
        ),
    ]
